"""'third'

Revision ID: 093be4118d77
Revises: e9392d11d57b
Create Date: 2023-03-02 16:36:51.533545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093be4118d77'
down_revision = 'e9392d11d57b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
