"""'second'

Revision ID: 3a55ebc5e9c2
Revises: 093be4118d77
Create Date: 2023-03-02 17:53:34.057192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a55ebc5e9c2'
down_revision = '093be4118d77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
