"""'fourth'

Revision ID: 76b9b0ff8410
Revises: 3a55ebc5e9c2
Create Date: 2023-03-05 18:12:02.477086

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '76b9b0ff8410'
down_revision = '3a55ebc5e9c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('owner_uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['owner_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['post_uid'], ['post.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
