"""'second'

Revision ID: e9392d11d57b
Revises: 403aa492a3e4
Create Date: 2023-03-02 13:32:54.129321

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e9392d11d57b'
down_revision = '403aa492a3e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('token', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('user_uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
